/**
 * File: ExcDemo2.java
 * @author Mallikarjuna00G
 * Purpose: An exception can be generated by one
 * method and caught by another.
 */
/**
 * Purpose: 
 */
class ExcTest {
    /*==================== START: FIELDS ====================*/
    
    /*==================== END: FIELDS ====================*/
    /*==================== START: CONSTRUCTORS ====================*/
    
    /*==================== END: CONSTRUCTORS ====================*/
    /*==================== START: ACCESSOR (SET and GET) METHODS ====================*/
    
    /*==================== END: ACCESSOR (SET and GET) METHODS ====================*/
    /*==================== START: METHODS ====================*/
    /**
     * Purpose: Generate an exception.
     */
    static void genException() {
        int[] nums = new int[4];

        System.out.println("Before exception is generated.");

        // generate an index out-of-bounds exception
        nums[7] = 10;
        System.out.println("This won't be displayed.");
    }  // method ExcTest
    /*==================== END: METHODS ====================*/
}  // class ExcTest

/**
 * Purpose: 
 */
class ExcDemo2 {
    public static void main(String[] args) {
        try {
            /*
             *Purpose: 
             */
            ExcTest.genException();
        }  // try statement
        catch(ArrayIndexOutOfBoundsException exc) {
            /*
             *Purpose: Catch the exception
             */
            System.out.println("Index out-of-bounds!");
        }  // catch exception type ArrayIndexOutOfBoundsException
        System.out.println("After catch statement");
    }  // main(String[])
}  // class ExcDemo2