# JBG_HS_Ch09_SelfTest

## SelfTest01

### SelfTest Problem

What class is at the top of the exception hierarchy?

### SelfTest Solution

`Throwable` is at the top of the exception hierarchy.

---
---

## SelfTest02

### SelfTest Problem

Briefly explain how to use `try` and `catch`.

### SelfTest Solution

The `try` and `catch` statements work together. Program statements that you want to monitor for exceptions are contained within a `try` block. An exception is caught using `catch`.

---
---

## SelfTest03

### SelfTest Problem

What is wrong with this fragment?

```java
// ...
vals[18] = 10;
catch (ArrayIndexOutOfBoundsException exc) {
    // handle error
}
```

### SelfTest Solution

There is no `try` block preceding the `catch` statement.

---
---

## SelfTest04

### SelfTest Problem

What happens if an exception is not caught?

### SelfTest Solution

If an exception is not caught, abnormal program termination results.

---
---

## SelfTest05

### SelfTest Problem

What is wrong with this fragment?

```java
class A extends Exception { ... }

class B extends A {
    ...
    // ...

    try {
        // ...
    }
    catch (A exc) { ... }
    catch (B exc) { ... }
}
```

### SelfTest Solution

In the fragment, a superclass `catch` precedes a subclass `catch`. Since the superclass `catch` will catch all subclasses too, unreachable code is created.

---
---

## SelfTest06

### SelfTest Problem

Can an inner `catch` rethrow an exception to an outer `catch`?

### SelfTest Solution

Yes, an exception can be rethrown.

---
---

## SelfTest07

### SelfTest Problem

The `finally` block is the last bit of code executed before your program ends. True or False? Explain your answer.

### SelfTest Solution

False. The `finally` block is the code executed when a `try` block ends.

---
---

## SelfTest08

### SelfTest Problem

What type of exceptions must be explicitly declared in a `throws` clause of a method?

### SelfTest Solution

All exceptions except those of type `RuntimeException` and `Error` must be declared in a `throws` clause.

---
---

## SelfTest09

### SelfTest Problem

What is wrong with this fragment?

```java
class MyClass {
    // ...
}

// ...

throw new MyClass();
```

### SelfTest Solution

`MyClass` does not extend `Throwable`. Only subclasses of `Throwable` can be thrown by `throw`.

---
---

## SelfTest10

### SelfTest Problem

In question 3 of the Chapter 6 Self Test, you created a `Stack` class. Add custom exceptions to your class that report stack full and stack empty conditions.

### SelfTest Solution

#### Source codes: 
- [Stack.java](./Stack.java)
- [StackEmptyException.java](./StackEmptyException.java)
- [StackFullException.java](./StackFullException.java)

---
---

## SelfTest11

### SelfTest Problem

What are the three ways that an exception can be generated?

### SelfTest Solution

An exception can be generated by an error in the JVM, by an error in your program, or explicitly via a `throw` statement.

---
---

## SelfTest12

### SelfTest Problem

What are the two direct subclasses of `Throwable`?

### SelfTest Solution

`Error` and `Exception`.

---
---

## SelfTest13

### SelfTest Problem

What is the multi-Â­catch feature?

### SelfTest Solution

The multi-catch feature allows one `catch` clause to catch two or more exceptions.

---
---

## SelfTest14

### SelfTest Problem

Should your code typically catch exceptions of type *Error*?

### SelfTest Solution

No.

---
---

